# Generated by Django 4.2.7 on 2023-11-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('document', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=11)),
                ('profile_type', models.CharField(choices=[('COMMON', 'Common'), ('MERCHANT', 'Merchant')], max_length=100)),
            ],
        ),
    ]
