# Generated by Django 4.2.7 on 2023-11-10 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_transactions_receiver_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='receiver_profile',
            new_name='receiver_profile_id',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='sender_profile',
            new_name='sender_profile_id',
        ),
    ]
